name: CHANGELOG.md update

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Generate Changelog
        uses: orhun/git-cliff-action@v4.8.0
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
      - name: Commit and Push
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@github.com'
          git add CHANGELOG.md
          git commit -m 'chore: update CHANGELOG.md'
          git push

